### ISSUE TITLE
bug at self.actionImportPC.triggered.connect(self.import_PC)

### ISSUE THREAD

**Issue by andrea-bistacchi** [andrea-bistacchi/PZero#13]
after the last commit I have a bug at [this line in project_window.py](https://github.com/andrea-bistacchi/PZero/blob/27689ba443f79c7ff88f3c609166bda8ca56eb72/pzero/project_window.py#L129).

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.1.3\plugins\python\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.1.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/_REPOS/PZero/pzero.py", line 7, in <module>
    project_window = ProjectWindow()
  File "D:\_REPOS\PZero\pzero\project_window.py", line 129, in __init__
    self.actionImportPC.triggered.connect(self.import_PC)
AttributeError: 'ProjectWindow' object has no attribute 'actionImportPC'``

**Comment by gbene** [comment]
Fixed. For some reason the action "import Point Cloud" was missing from the project_window.ui file.

**Comment by andrea-bistacchi** [comment]
Are you syncing on GitHub also the GUI files modified with Qt Designer?

**Comment by gbene** [comment]
With this fix yes. In one of the very first pushes of the festure_PCDom branch I added the qaction directly in the code without using the qtdesigner so the .UI file was not up to date.

**Comment by andrea-bistacchi** [comment]
Ok let's keep the Designer file in sync.
